<?php
/**
 * RapportApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Module d'enregistrement des ventes (MEV) API
 *
 * Permet la communication bidirectionnelle avec le module d'enregistrement des ventes (MEV) de Revenu Québec et votre système d'enregistrement des ventes (SEV) ou toutes autres logiciel de caisse.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@mev.quebec
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mev\Gateway;

use Mev\Gateway\Configuration;
use Mev\Gateway\ApiException;
use Mev\Gateway\ObjectSerializer;

/**
 * RapportApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RapportApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for analyseTransactionnelle
     *
     * Analyse transactionnelle (par période).
     *
     */
    public function testAnalyseTransactionnelle()
    {
    }

    /**
     * Test case for analyseTransactionnelleTransaction
     *
     * Analyse transactionnelle (par numéro de transaction)).
     *
     */
    public function testAnalyseTransactionnelleTransaction()
    {
    }

    /**
     * Test case for detailDesVentesNonPrescrit
     *
     * Détail des ventes (non prescrit, par période).
     *
     */
    public function testDetailDesVentesNonPrescrit()
    {
    }

    /**
     * Test case for detailDesVentesPrescritPartiel
     *
     * Détail des ventes (prescrit partiel, par numéro de transaction).
     *
     */
    public function testDetailDesVentesPrescritPartiel()
    {
    }

    /**
     * Test case for detailJournalEvenements
     *
     * Détail du journal des évènements.
     *
     */
    public function testDetailJournalEvenements()
    {
    }

    /**
     * Test case for infosGenerales
     *
     * Informations générales.
     *
     */
    public function testInfosGenerales()
    {
    }

    /**
     * Test case for sommaireDesVentes
     *
     * Rapport Sommaire des ventes par période.
     *
     */
    public function testSommaireDesVentes()
    {
    }

    /**
     * Test case for sommaireDesVentesTransaction
     *
     * Rapport Sommaire des ventes par numéro de transaction.
     *
     */
    public function testSommaireDesVentesTransaction()
    {
    }

    /**
     * Test case for sommaireJournalEvenements
     *
     * Sommaire du journal des évènements.
     *
     */
    public function testSommaireJournalEvenements()
    {
    }

    /**
     * Test case for sommairePeriodiqueDesVentes
     *
     * Rapport Sommaire périodique des ventes.
     *
     */
    public function testSommairePeriodiqueDesVentes()
    {
    }
}
