<?php
/**
 * SystemeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Module d'enregistrement des ventes (MEV) API
 *
 * Permet la communication bidirectionnelle avec le module d'enregistrement des ventes (MEV) de Revenu Québec et votre système d'enregistrement des ventes (SEV) ou toutes autres logiciel de caisse.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@mev.quebec
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mev\Gateway;

use Mev\Gateway\Configuration;
use Mev\Gateway\ApiException;
use Mev\Gateway\ObjectSerializer;

/**
 * SystemeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for effacerModele
     *
     * Efface un modèle de facture en attente.
     *
     */
    public function testEffacerModele()
    {
    }

    /**
     * Test case for listeModele
     *
     * Obtenir les informations d'un modèle de facture spécifique.
     *
     */
    public function testListeModele()
    {
    }

    /**
     * Test case for listeModeleFacture
     *
     * Liste des modèles de facture.
     *
     */
    public function testListeModeleFacture()
    {
    }

    /**
     * Test case for systemeModelesPost
     *
     * Ajouter un nouveau modèle de facture.
     *
     */
    public function testSystemeModelesPost()
    {
    }
}
