<?php
/**
 * TransactionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Module d'enregistrement des ventes (MEV) API
 *
 * Permet la communication bidirectionnelle avec le module d'enregistrement des ventes (MEV) de Revenu Québec et votre système d'enregistrement des ventes (SEV) ou toutes autres logiciel de caisse.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@mev.quebec
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Mev\Gateway;

use Mev\Gateway\Configuration;
use Mev\Gateway\ApiException;
use Mev\Gateway\ObjectSerializer;

/**
 * TransactionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mev\Gateway
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for annuleTransaction
     *
     * Annule la transmission d'une transaction en attente.
     *
     */
    public function testAnnuleTransaction()
    {
    }

    /**
     * Test case for getTransaction
     *
     * Obtenir les informations d'une transaction spécifique.
     *
     */
    public function testGetTransaction()
    {
    }

    /**
     * Test case for getTransactionFile
     *
     * Téléchargement de fichier.
     *
     */
    public function testGetTransactionFile()
    {
    }

    /**
     * Test case for getTransactionStatus
     *
     * Obtenir les informations d'une transaction spécifique.
     *
     */
    public function testGetTransactionStatus()
    {
    }

    /**
     * Test case for listeTransaction
     *
     * Liste des transactions.
     *
     */
    public function testListeTransaction()
    {
    }
}
